#
# MAINTAINER        Leo.Meng <fivestarsky@gmail.com>
# DOCKER-VERSION    1.7.0
#
# Dockerizing CentOS7: Dockerfile for building CentOS images
#
FROM       busybox
MAINTAINER Leo.Meng <Leo.Meng@gmail.com>

ENV TZ "Asia/Shanghai"

